### ISSUE TITLE
2nd, 3rd, 4th images are dropped down about 20 px

### ISSUE THREAD

**Issue by digibrink** [benschwarz/gallery-css#11]
Hi,

This is great but I am having a few issues. All secondary images in the slideshow (1 is good, 2-5 are off) are dropped down and I can't get them positioned correctly. See screenshots. Any help would be greatly appreciated. Thanks!!

Justin

![screen shot 2014-03-25 at 6 50 47 pm](https://f.cloud.github.com/assets/7063985/2519326/080e2664-b470-11e3-9245-37ee012b9ae9.png)
![screen shot 2014-03-25 at 6 51 24 pm](https://f.cloud.github.com/assets/7063985/2519327/081906a6-b470-11e3-96db-a5f377385998.png)
![screen shot 2014-03-25 at 6 51 37 pm](https://f.cloud.github.com/assets/7063985/2519328/081dac92-b470-11e3-842b-76acc664b719.png)
![screen shot 2014-03-25 at 6 51 55 pm](https://f.cloud.github.com/assets/7063985/2519329/08229608-b470-11e3-8b05-23aa8a54d0a6.png)

**Comment by dharapvj** [comment]
Exactly my issue too!

My reset was incorrect! saved my day..
