### ISSUE TITLE
Examples are either incomplete or of poor taste

### ISSUE THREAD

**Issue by benschwarz** [benschwarz/gallery-css#15]
- Examples use prefixfree, which sucks for non-http serving (#10)
- Examples have incomplete formatting, which sucks for taking and using (#11)
- Examples should demonstrate best usage practice
- Generally, people are having trouble (#13, #6)

Aim: 

Cleanup `/examples` and make it easier to get started with Gallery 

Lets do this!

**Comment by yoDon** [comment]
Not so much as a screenshot anywhere in the docs? For a visual thing like a photo gallery? Presumably that means you're more proud of the CSS selector techniques you're trying to sell us than you are of how this project actually looks.

**Comment by benschwarz** [comment]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/924/65381235-67bb2f00-dd30-11e9-89eb-008d034ef264.png">

**Comment by benschwarz** [comment]
The author decided to leave abuse and later deleted it. 👎
