### ISSUE TITLE
links failed during the first seconds of the animation

### ISSUE THREAD

**Issue by jairusgit** [benschwarz/gallery-css#17]
Hello,

I am doing two galleries with 5 items and autoplay using your awesome work. I've bought and saw your video but I still have a problem:

If I click on the control button for the 2nd image before it appears on the animation (5 seconds), it shows a blank div, if then I click in the first control button, everything works fine.
This happens for the rest of the images if I click on the control button before its delay-animation.
Do you know if there is a way to solve this?

Please let me know if you need more info, the webpage is http://95.85.58.103/jardineriacanizo/index.php

Thanks in advance,
Jairo García

**Comment by nurupo** [comment]
Sounds like this issue could be closed now.

**Comment by benschwarz** [comment]
Thanks @nurupo
