### ISSUE TITLE
Links on figcaptione

### ISSUE THREAD

**Issue by dailybread81** [benschwarz/gallery-css#18]
I've linked a caption in each slide.. but it works only the first and when it has slide away the other links won't work. It seems to be the first caption always on top!

**Comment by workinprogresz** [comment]
encountered similar issue recently. It's because the height of the slide is set to 100% and it overlaps the navigation dot. Decreased the height to 90% so the dots can register the click.

**Comment by benschwarz** [comment]
@workinprogresz is there something that could be PRd to this repo? 

If there's an ongoing problem and you've solved it, it'd make for a great contribution 😎
