### ISSUE TITLE
Getting the slider to change slides 

### ISSUE THREAD

**Issue by netweavemedia-nick** [benschwarz/gallery-css#24]
Hello, I was wondering if you would be able to help me. We are trying to add swipe detection to the gallery (using hammerjs) and I was wondering how I could trigger the slide to change depending on which way the slide went. 

The only requirement is that it cannot use jQuery. 

Thanks.

**Comment by benschwarz** [comment]
There are a few reasons why this wouldn't work out — as you're probably aware, gallery-css fades inbeteeen slides; "swiping through" something that fades in this manner will feel 100% incorrect.

​

​Not so say that you can't do what you want here, I'm just not convinced that you should.

**Comment by netweavemedia-nick** [comment]
Okay thanks. I thought not, thanks for your help :)
