### ISSUE TITLE
No Source Code About http://benschwarz.github.io/gallery-css/

### ISSUE THREAD

**Issue by WaylanPunch** [benschwarz/gallery-css#26]
When I opened your web page - [**Gallery CSS**](http://benschwarz.github.io/gallery-css/), I read the [**code**](view-source:http://benschwarz.github.io/gallery-css/) of this page through the Browser. But I cannot find resource like 

```
"images/arrow-left.svg"  or "images/arrow-right.svg"
```

I quite fancy the style of your work, but where the source code you put in? I can't find them in your public repositories.

**Comment by enociz** [comment]
Have you tried the gh-pages branch?



Regards,


Enoch Appathurai

**Comment by benschwarz** [comment]
Just a reminder that the assets used on the site (and the site itself) is not licensed, and has various copyright owners (the icons, for example), and should not be used by any one without expressed written permission.  This is not only to protect my copyright, but also others. :heartbeat:

**Comment by WaylanPunch** [comment]
OK! @benschwarz , Thanks for your patience ! I am noticed !
