### ISSUE TITLE
Stop Slideshow When Click On Vimeo Video

### ISSUE THREAD

**Issue by luispoll88** [benschwarz/gallery-css#29]
I am using the slideshow inside this website **FreshLoc.com** 

And on the first slide on that website I am using a Vimeo Video.

I am trying to see if I can stop the slideshow when someone clicks on the video.

Thanks,

Luis

**Comment by benschwarz** [comment]
You could try 'animation-play-state: paused', but tbh, I think you'd be better to remove the 'autoplay' class.
