### ISSUE TITLE
Css gallery safari overlap animation

### ISSUE THREAD

**Issue by Leon-86** [benschwarz/gallery-css#37]
hi, I have this site:

http://domar.laranciaweb.it/

but in safari the animation css overlap, why? :(

Thank you
![schermata 2017-11-21 alle 09 45 42](https://user-images.githubusercontent.com/33860201/33062784-caad5246-cea0-11e7-8051-2dfb36a8e20f.png)

**Comment by Leon-86** [comment]
Anyone?

**Comment by benschwarz** [comment]
Sorry @Leon-86, I don't have time to check this out for you.
